repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt --check
        entry: bash scripts/check_fmt.sh
        language: system
        pass_filenames: false
        always_run: true
      - id: cargo-clippy
        name: cargo clippy
        entry: bash scripts/check_clippy.sh
        language: system
        pass_filenames: false
        always_run: true
      - id: cargo-coverage
        name: coverage check
        entry: bash scripts/check_coverage.sh
        language: system
        pass_filenames: false
        always_run: true
